### ISSUE TITLE
Unstable test

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo-wallet#47]
property("AES encryption/decryption - failure on corrupted data decryption") fails with exception

```
    Gave up after 6 successful property evaluations. 51 evaluations were discarded.
ScalaTestFailureLocation: org.ergoplatform.wallet.crypto.EncryptionSpec at (EncryptionSpec.scala:30)
org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: Gave up after 6 successful property evaluations. 51 evaluations were discarded.
	at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:232)
	at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:220)
	at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:110)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:1333)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:1307)
	at org.ergoplatform.wallet.crypto.EncryptionSpec.forAll(EncryptionSpec.scala:9)
	at org.ergoplatform.wallet.crypto.EncryptionSpec.$anonfun$new$3(EncryptionSpec.scala:30)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

**Comment by greenhat** [comment]
I'm confirming this. It fails roughly on every other run.
